import { daysFromToday, isoDate, isoDateTime, nowIso, todayKey } from "@/lib/dates";
import type {
  Activity,
  Comment,
  FollowUp,
  Member,
  Sprint,
  Ticket,
  WorkLog,
  Workspace,
} from "@/lib/types";

const members: Member[] = [
  {
    id: "m-neeraj",
    name: "Neeraj PM",
    email: "neeraj@harbor.team",
    role: "product_owner",
    title: "Product Owner",
    initials: "NP",
    hue: 175,
    weeklyCapacityHours: 30,
    skills: ["roadmap", "prioritization", "stakeholder"],
  },
  {
    id: "m-maya",
    name: "Maya Chen",
    email: "maya@harbor.team",
    role: "scrum_master",
    title: "Scrum Master",
    initials: "MC",
    hue: 262,
    weeklyCapacityHours: 32,
    skills: ["facilitation", "coaching", "risk"],
  },
  {
    id: "m-arjun",
    name: "Arjun Patel",
    email: "arjun@harbor.team",
    role: "engineer",
    title: "Staff Engineer",
    initials: "AP",
    hue: 32,
    weeklyCapacityHours: 40,
    skills: ["payments", "backend", "architecture"],
  },
  {
    id: "m-sofia",
    name: "Sofia Alvarez",
    email: "sofia@harbor.team",
    role: "engineer",
    title: "Frontend Engineer",
    initials: "SA",
    hue: 340,
    weeklyCapacityHours: 40,
    skills: ["react", "design-system", "accessibility"],
  },
  {
    id: "m-kenji",
    name: "Kenji Nakamura",
    email: "kenji@harbor.team",
    role: "engineer",
    title: "Backend Engineer",
    initials: "KN",
    hue: 210,
    weeklyCapacityHours: 40,
    skills: ["ledger", "postgres", "webhooks"],
  },
  {
    id: "m-priya",
    name: "Priya Shah",
    email: "priya@harbor.team",
    role: "qa",
    title: "QA Engineer",
    initials: "PS",
    hue: 145,
    weeklyCapacityHours: 40,
    skills: ["regression", "automation", "payments-qa"],
  },
  {
    id: "m-liam",
    name: "Liam Okafor",
    email: "liam@harbor.team",
    role: "designer",
    title: "Product Designer",
    initials: "LO",
    hue: 48,
    weeklyCapacityHours: 35,
    skills: ["ux", "checkout", "research"],
  },
  {
    id: "m-elena",
    name: "Elena Rossi",
    email: "elena@harbor.team",
    role: "engineer",
    title: "Platform Engineer",
    initials: "ER",
    hue: 12,
    weeklyCapacityHours: 38,
    skills: ["observability", "sre", "queues"],
  },
];

function ticket(
  partial: Omit<Ticket, "createdAt" | "updatedAt"> & {
    createdOffset?: number;
    updatedOffset?: number;
  }
): Ticket {
  const created = isoDateTime(daysFromToday(partial.createdOffset ?? -10));
  const updated = isoDateTime(daysFromToday(partial.updatedOffset ?? -1));
  return {
    id: partial.id,
    key: partial.key,
    title: partial.title,
    description: partial.description,
    type: partial.type,
    status: partial.status,
    priority: partial.priority,
    storyPoints: partial.storyPoints,
    dueDate: partial.dueDate,
    labels: partial.labels,
    sprintId: partial.sprintId,
    assigneeId: partial.assigneeId,
    reporterId: partial.reporterId,
    blockedReason: partial.blockedReason,
    completedAt: partial.completedAt,
    createdAt: created,
    updatedAt: updated,
  };
}

export function createSeedWorkspace(): Workspace {
  const sprint23: Sprint = {
    id: "sprint-23",
    name: "Sprint 23",
    goal: "Ship wallet tokenization and close the refund-latency incident.",
    status: "completed",
    startDate: isoDate(daysFromToday(-21)),
    endDate: isoDate(daysFromToday(-8)),
  };
  const sprint24: Sprint = {
    id: "sprint-24",
    name: "Sprint 24",
    goal: "Make checkout retries trustworthy before the merchant summit.",
    status: "active",
    startDate: isoDate(daysFromToday(-7)),
    endDate: isoDate(daysFromToday(4)),
  };
  const sprint25: Sprint = {
    id: "sprint-25",
    name: "Sprint 25",
    goal: "Start installment plans and harden webhook delivery.",
    status: "planning",
    startDate: isoDate(daysFromToday(7)),
    endDate: isoDate(daysFromToday(18)),
  };

  const tickets: Ticket[] = [
    ticket({
      id: "AM-118",
      key: "AM-118",
      title: "Retry banner copy for failed card charges",
      description:
        "When a card is declined, show a calm retry path with the decline reason mapped to merchant-safe language. Design is in Figma, engineering needs the banner, toast, and analytics event.",
      type: "story",
      status: "in_progress",
      priority: "high",
      storyPoints: 5,
      dueDate: isoDate(daysFromToday(0)),
      labels: ["checkout", "copy"],
      sprintId: "sprint-24",
      assigneeId: "m-sofia",
      reporterId: "m-liam",
      blockedReason: null,
      completedAt: null,
      createdOffset: -12,
      updatedOffset: -3,
    }),
    ticket({
      id: "AM-121",
      key: "AM-121",
      title: "Idempotent retry of capture API",
      description:
        "Capture retries are double-charging a small set of sandbox merchants. Add an idempotency key on capture and a replay-safe ledger write.",
      type: "story",
      status: "in_progress",
      priority: "critical",
      storyPoints: 8,
      dueDate: isoDate(daysFromToday(1)),
      labels: ["payments", "ledger"],
      sprintId: "sprint-24",
      assigneeId: "m-arjun",
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: null,
      createdOffset: -9,
      updatedOffset: 0,
    }),
    ticket({
      id: "AM-109",
      key: "AM-109",
      title: "Webhook retry storm after 429s",
      description:
        "Partner webhooks retry immediately on 429 and flood the worker pool. Need jittered backoff and a circuit breaker per destination.",
      type: "bug",
      status: "in_review",
      priority: "critical",
      storyPoints: 5,
      dueDate: isoDate(daysFromToday(-1)),
      labels: ["webhooks", "reliability"],
      sprintId: "sprint-24",
      assigneeId: "m-elena",
      reporterId: "m-maya",
      blockedReason: null,
      completedAt: null,
      createdOffset: -14,
      updatedOffset: 0,
    }),
    ticket({
      id: "AM-124",
      key: "AM-124",
      title: "QA matrix for 3DS challenge recovery",
      description:
        "Cover happy path, abandoned challenge, timeout, and issuer-unavailable. Automate the two most common paths in Playwright.",
      type: "task",
      status: "todo",
      priority: "high",
      storyPoints: 3,
      dueDate: isoDate(daysFromToday(2)),
      labels: ["qa", "3ds"],
      sprintId: "sprint-24",
      assigneeId: "m-priya",
      reporterId: "m-maya",
      blockedReason: null,
      completedAt: null,
      createdOffset: -6,
      updatedOffset: -2,
    }),
    ticket({
      id: "AM-126",
      key: "AM-126",
      title: "Checkout empty-cart illustration refresh",
      description:
        "Replace the old empty state with the Harbor mark and a single recovery CTA. No engineering beyond asset swap.",
      type: "task",
      status: "todo",
      priority: "low",
      storyPoints: 2,
      dueDate: isoDate(daysFromToday(3)),
      labels: ["design", "checkout"],
      sprintId: "sprint-24",
      assigneeId: "m-liam",
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: null,
      createdOffset: -5,
      updatedOffset: -4,
    }),
    ticket({
      id: "AM-112",
      key: "AM-112",
      title: "Ledger outbox publisher stuck on poison message",
      description:
        "A malformed refund event is blocking the outbox. Need a dead-letter path and operator replay.",
      type: "bug",
      status: "in_progress",
      priority: "critical",
      storyPoints: 8,
      dueDate: isoDate(daysFromToday(-2)),
      labels: ["ledger", "incident"],
      sprintId: "sprint-24",
      assigneeId: "m-kenji",
      reporterId: "m-arjun",
      blockedReason: "Waiting on infra to raise the DLQ retention from 1h to 7d.",
      completedAt: null,
      createdOffset: -11,
      updatedOffset: -4,
    }),
    ticket({
      id: "AM-130",
      key: "AM-130",
      title: "Merchant summit demo script",
      description:
        "Write the live demo path: decline → retry → success, plus the backup recording if sandbox is noisy.",
      type: "task",
      status: "todo",
      priority: "high",
      storyPoints: 2,
      dueDate: isoDate(daysFromToday(3)),
      labels: ["enablement"],
      sprintId: "sprint-24",
      assigneeId: "m-neeraj",
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: null,
      createdOffset: -3,
      updatedOffset: -1,
    }),
    ticket({
      id: "AM-115",
      key: "AM-115",
      title: "Sprint health digest for leadership",
      description:
        "Weekly rollup: sprint goal risk, overdue work, and a one-line ask. Coach can draft this.",
      type: "task",
      status: "done",
      priority: "medium",
      storyPoints: 1,
      dueDate: isoDate(daysFromToday(-3)),
      labels: ["process"],
      sprintId: "sprint-24",
      assigneeId: "m-maya",
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: isoDateTime(daysFromToday(-3)),
      createdOffset: -8,
      updatedOffset: -3,
    }),
    ticket({
      id: "AM-119",
      key: "AM-119",
      title: "Trace sampling on checkout span",
      description:
        "Raise sampling on checkout.attempt spans during the summit week without exploding Grafana cost.",
      type: "task",
      status: "done",
      priority: "medium",
      storyPoints: 3,
      dueDate: isoDate(daysFromToday(-1)),
      labels: ["observability"],
      sprintId: "sprint-24",
      assigneeId: "m-elena",
      reporterId: "m-maya",
      blockedReason: null,
      completedAt: isoDateTime(daysFromToday(-1)),
      createdOffset: -7,
      updatedOffset: -1,
    }),
    ticket({
      id: "AM-107",
      key: "AM-107",
      title: "Saved card tokenization (Sprint 23 carryover)",
      description:
        "Vault tokens for returning shoppers. Shipped last sprint; keeping the record for velocity math.",
      type: "story",
      status: "done",
      priority: "high",
      storyPoints: 8,
      dueDate: isoDate(daysFromToday(-9)),
      labels: ["wallet"],
      sprintId: "sprint-23",
      assigneeId: "m-arjun",
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: isoDateTime(daysFromToday(-9)),
      createdOffset: -20,
      updatedOffset: -9,
    }),
    ticket({
      id: "AM-108",
      key: "AM-108",
      title: "Refund latency SLO dashboard",
      description: "Grafana board for p95 refund completion. Closed in Sprint 23.",
      type: "story",
      status: "done",
      priority: "medium",
      storyPoints: 5,
      dueDate: isoDate(daysFromToday(-8)),
      labels: ["observability"],
      sprintId: "sprint-23",
      assigneeId: "m-elena",
      reporterId: "m-maya",
      blockedReason: null,
      completedAt: isoDateTime(daysFromToday(-10)),
      createdOffset: -19,
      updatedOffset: -10,
    }),
    ticket({
      id: "AM-132",
      key: "AM-132",
      title: "Installment plan eligibility rules",
      description:
        "Define who can offer 3/6/12 month plans. Needs legal sign-off before engineering estimates.",
      type: "spike",
      status: "backlog",
      priority: "medium",
      storyPoints: 3,
      dueDate: isoDate(daysFromToday(10)),
      labels: ["installments", "spike"],
      sprintId: "sprint-25",
      assigneeId: null,
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: null,
      createdOffset: -2,
      updatedOffset: -2,
    }),
    ticket({
      id: "AM-133",
      key: "AM-133",
      title: "Webhook signing key rotation",
      description: "Rotate signing keys with a dual-publish window so partners do not drop events.",
      type: "story",
      status: "backlog",
      priority: "high",
      storyPoints: 5,
      dueDate: isoDate(daysFromToday(12)),
      labels: ["webhooks", "security"],
      sprintId: "sprint-25",
      assigneeId: "m-kenji",
      reporterId: "m-arjun",
      blockedReason: null,
      completedAt: null,
      createdOffset: -1,
      updatedOffset: -1,
    }),
    ticket({
      id: "AM-134",
      key: "AM-134",
      title: "Accessible decline reason live region",
      description:
        "Screen readers miss the decline toast. Sofia flagged this in review; needs a polite live region and focus return.",
      type: "bug",
      status: "backlog",
      priority: "high",
      storyPoints: 3,
      dueDate: null,
      labels: ["a11y", "checkout"],
      sprintId: null,
      assigneeId: "m-sofia",
      reporterId: "m-priya",
      blockedReason: null,
      completedAt: null,
      createdOffset: -1,
      updatedOffset: -1,
    }),
    ticket({
      id: "AM-135",
      key: "AM-135",
      title: "Nightly checkout smoke on staging",
      description: "Cron a Playwright smoke against staging after deploys. Unassigned — good candidate for Priya.",
      type: "task",
      status: "backlog",
      priority: "medium",
      storyPoints: 5,
      dueDate: null,
      labels: ["qa", "ci"],
      sprintId: null,
      assigneeId: null,
      reporterId: "m-maya",
      blockedReason: null,
      completedAt: null,
      createdOffset: 0,
      updatedOffset: 0,
    }),
    ticket({
      id: "AM-122",
      key: "AM-122",
      title: "Capture receipt email localization",
      description: "EN/ES/JA templates for capture receipts. Copy is late from localization.",
      type: "story",
      status: "todo",
      priority: "medium",
      storyPoints: 5,
      dueDate: isoDate(daysFromToday(4)),
      labels: ["email", "i18n"],
      sprintId: "sprint-24",
      assigneeId: null,
      reporterId: "m-neeraj",
      blockedReason: null,
      completedAt: null,
      createdOffset: -4,
      updatedOffset: -4,
    }),
  ];

  const workLogs: WorkLog[] = [
    {
      id: "wl-arjun-1",
      memberId: "m-arjun",
      date: isoDate(daysFromToday(-1)),
      yesterday: "Idempotency middleware drafted; added failing tests for double capture.",
      today: "Finish ledger write path and pair with Kenji on outbox poison message.",
      blockers: "",
      hoursLogged: 7.5,
      mood: "stretched",
      ticketIds: ["AM-121", "AM-112"],
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "wl-sofia-1",
      memberId: "m-sofia",
      date: isoDate(daysFromToday(-1)),
      yesterday: "Banner component in, waiting on final decline-reason map from Liam.",
      today: "Wire analytics event and handle the 3DS return path.",
      blockers: "Need the copy matrix before I can close AM-118 today.",
      hoursLogged: 6.5,
      mood: "on_track",
      ticketIds: ["AM-118"],
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "wl-kenji-1",
      memberId: "m-kenji",
      date: isoDate(daysFromToday(-1)),
      yesterday: "Reproduced the poison message; DLQ PR is blocked on retention config.",
      today: "Ping platform for the retention bump, then finish operator replay.",
      blockers: "DLQ retention still 1 hour — cannot safely replay.",
      hoursLogged: 6,
      mood: "blocked",
      ticketIds: ["AM-112"],
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "wl-elena-1",
      memberId: "m-elena",
      date: isoDate(daysFromToday(-1)),
      yesterday: "Backoff + jitter merged; writing the review notes for AM-109.",
      today: "Respond to review comments and watch staging error budget.",
      blockers: "",
      hoursLogged: 7,
      mood: "on_track",
      ticketIds: ["AM-109", "AM-119"],
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "wl-priya-1",
      memberId: "m-priya",
      date: isoDate(daysFromToday(-1)),
      yesterday: "Sketched the 3DS matrix; two Playwright stubs.",
      today: "Need a stable sandbox challenge. Will start AM-124 in earnest.",
      blockers: "Sandbox 3DS is flaky after 17:00 UTC.",
      hoursLogged: 5,
      mood: "stretched",
      ticketIds: ["AM-124"],
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "wl-maya-1",
      memberId: "m-maya",
      date: isoDate(daysFromToday(-1)),
      yesterday: "Sent the health digest. Flagged AM-112 as sprint risk.",
      today: "Unblock Kenji with platform, then run due-date follow-ups.",
      blockers: "",
      hoursLogged: 6,
      mood: "on_track",
      ticketIds: ["AM-115", "AM-112"],
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "wl-arjun-2",
      memberId: "m-arjun",
      date: isoDate(daysFromToday(-2)),
      yesterday: "Mapped capture retry races in staging logs.",
      today: "Spike idempotency key design with Elena.",
      blockers: "",
      hoursLogged: 8,
      mood: "stretched",
      ticketIds: ["AM-121"],
      createdAt: isoDateTime(daysFromToday(-2)),
    },
    {
      id: "wl-liam-2",
      memberId: "m-liam",
      date: isoDate(daysFromToday(-2)),
      yesterday: "Decline-reason copy v2 in Figma.",
      today: "Empty-cart illustration and a pass on the demo script with Neeraj.",
      blockers: "",
      hoursLogged: 5.5,
      mood: "on_track",
      ticketIds: ["AM-118", "AM-126"],
      createdAt: isoDateTime(daysFromToday(-2)),
    },
  ];

  const comments: Comment[] = [
    {
      id: "c1",
      ticketId: "AM-118",
      memberId: "m-liam",
      body: "Copy matrix is in Figma page 'Decline reasons v3'. Two strings still with legal.",
      createdAt: isoDateTime(daysFromToday(-2)),
    },
    {
      id: "c2",
      ticketId: "AM-112",
      memberId: "m-kenji",
      body: "Cannot proceed until DLQ retention is at least 7 days. Posted in #platform.",
      createdAt: isoDateTime(daysFromToday(-4)),
    },
    {
      id: "c3",
      ticketId: "AM-109",
      memberId: "m-arjun",
      body: "Backoff looks right. Please add a metric for 'retries_suppressed'.",
      createdAt: isoDateTime(daysFromToday(0)),
    },
  ];

  const followUps: FollowUp[] = [
    {
      id: "fu-1",
      ticketId: "AM-112",
      memberId: "m-kenji",
      type: "overdue",
      message:
        "Kenji — AM-112 (Ledger outbox poison message) is 2 days past due and still blocked on DLQ retention. Need a status by standup: is platform unblocked, or should we cut a narrower patch for the summit?",
      status: "pending",
      createdAt: isoDateTime(daysFromToday(0)),
      sentAt: null,
    },
    {
      id: "fu-2",
      ticketId: "AM-118",
      memberId: "m-sofia",
      type: "due_today",
      message:
        "Sofia — AM-118 is due today. Banner is in progress and last updated 3 days ago. If legal copy is still out, move the due date and leave a note so the board stays honest.",
      status: "pending",
      createdAt: isoDateTime(daysFromToday(0)),
      sentAt: null,
    },
  ];

  const activity: Activity[] = [
    {
      id: "a1",
      type: "status",
      message: "Elena moved AM-109 into In review.",
      memberId: "m-elena",
      ticketId: "AM-109",
      createdAt: isoDateTime(daysFromToday(0)),
    },
    {
      id: "a2",
      type: "log",
      message: "Arjun filed yesterday's work log (7.5h, stretched).",
      memberId: "m-arjun",
      ticketId: "AM-121",
      createdAt: isoDateTime(daysFromToday(-1)),
    },
    {
      id: "a3",
      type: "done",
      message: "Maya completed AM-115 Sprint health digest.",
      memberId: "m-maya",
      ticketId: "AM-115",
      createdAt: isoDateTime(daysFromToday(-3)),
    },
  ];

  return {
    settings: {
      projectName: "Harbor Checkout",
      projectKey: "AM",
      teamName: "Harbor Squad",
      nextTicketNumber: 136,
    },
    members,
    sprints: [sprint25, sprint24, sprint23],
    tickets,
    workLogs,
    comments,
    followUps,
    activity,
    agentMessages: [
      {
        id: "am-welcome",
        role: "assistant",
        content:
          `Good morning. I am the Harbor Agile Coach. Today is ${todayKey()}. Sprint 24 still has a blocked critical (AM-112), a due-today story (AM-118), and two people who have not logged work yet. Ask me to run a due-date sweep, draft follow-ups, assign unowned tickets, or brief you on sprint risk.`,
        createdAt: nowIso(),
      },
    ],
  };
}
